### ISSUE TITLE
The link is wrong in the description

### ISSUE THREAD

**Issue by jpwhitney** [NeoGeographyToolkit/BinaryBuilder#10]
On the project page: https://github.com/NeoGeographyToolkit/BinaryBuilder the link at the top

> Script for generating the binary builds of Stereo Pipeline http://ti.arc.nasa.gov/tech/asr/intel…

Is incorrect.

It should be: https://ti.arc.nasa.gov/tech/asr/groups/intelligent-robotics/ngt/stereo/

**Comment by ScottMcMichael** [comment]
Fixed, thanks!
