### ISSUE TITLE
Creation of DEM from aerial photographs

### ISSUE THREAD

**Issue by jpwhitney** [NeoGeographyToolkit/BinaryBuilder#11]
Can this be used to create a DEM from multiple aerial photos? For example photos from a DJI drone.

Thanks.

**Comment by ScottMcMichael** [comment]
BinaryBuilder is only for building our software from scratch which very few people actually need to do.  Unless you want to write you own custom code, download Ames Stereo Pipeline from our website: https://ti.arc.nasa.gov/tech/asr/groups/intelligent-robotics/ngt/stereo/
