### ISSUE TITLE
RHEL needs cmake28

### ISSUE THREAD

**Issue by SmithB** [NeoGeographyToolkit/BinaryBuilder#5]
Some packages (Lapack for one) require a more recent version of cmake than redhat enterprise supplies.  It's possible to install a cmake28 package that provides cmake 2.8, but the executable it provides is called cmake28, not cmake.  Changing the line
cmake='cmake'
in Binarbuilder.py to
cmake='cmake28'
appears to fix this problem.  Binarybuilder.py should check for the cmake version and if it's less than 2.8, check if cmake28 exists.

**Comment by oleg-alexandrov** [comment]
Somehow I was never notified when BinaryBuilder issues get posted. Three years too late, now BinaryBuilder builds its own cmake (version 3.2.3) so this problem went away. Jotting this down for the record.
